services:
 mysqldb:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userinfo
    container_name: mysqldb
 sql:
    build: C:\Users\JIT\Documents\Docker\sql\Dockerfile
    depends_on:
      - mysqldb
